# Generated by Django 4.2.16 on 2024-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='car',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='prod',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
