# Generated by Django 4.2.16 on 2024-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_car_checkout_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='car',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='prod',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.CharField(max_length=200000, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.CharField(max_length=50000, null=True),
        ),
    ]
