# Generated by Django 4.2.16 on 2024-11-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
