# Generated by Django 4.2.16 on 2024-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_brand_alter_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
