# Generated by Django 4.2.16 on 2024-11-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_car_product_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='car',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod',
        ),
    ]
